# image metadata and thumbnails are stored here
database: /db/pica.db?mode=rwc

# size of thumbnails
thumbSize: 256

# size of preview images
previewSize: 2048

# Create thumbnails and preview images on first access
lazyThumbs: true

# number of threads to use for indexing
indexerThreads: 4

# Use image magick to generate thumbnails. This is generally faster than using
# the inbuilt encoder, especially for encoding avif files.
# It requires 'convert' on the PATH.
useImageMagick: true

# The image codec to use to encode thumbnails.
# This can be jpeg or avif.
imageCodec: avif

# If the original file is an UltraHDR file, we might prefer to create thumbnail and preview
# image as ultra hdr too. This takes preferences over the configured imageCodec.
preferUltraHdr: true

# Maximum amount of memory to use.
# This is an approximation used when encoding images. Each image that is currently being encoded
# is counted with (width * height * 4) byte to this limit.
maxMemoryInMegabytes: 1024

# Time between two consecutive scans of the filesystem for new files to index.
scanIntervalInSeconds: 30

# Address to bind the http server to.
httpAddress: 0.0.0.0:3000

# Set to false to not allow access over http. This controls the 'Secure' attribute
# on the login cookie. If you serve pica over https, best set this to 'false'.
allowAccessOverHTTP: true

# Specify jaeger tracing endpoint, or comment out for no tracing
# jaegerTracing: 192.168.86.5:6831

users:
  - name: admin

    # the password hash as given by `htpasswd -n -B -C 7 ignored | cut -d: -f2-`
    # default value is 'docker'.
    passwd: $2y$07$vhLM7t39q9VNvc7m5r9cgeSFgFrOIMbHtXIxT.ZiNiuKmIsfUH.5u

sources:
  - name: Photos
    access: [ user ]
    path: /photos
