[package]
name = "pica"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = "thin"
codegen-units = 1

[dependencies]
anyhow = "1.0.76"
axum = "0.7.2"
byteorder = "1.5.0"
chrono = { version = "0.4.31", features = ["serde"] }
csv = "1.3.0"
derive_more = "0.99.17"
flate2 = "1.0.28"
hex = "0.4.3"
hex-literal = "0.4.1"
image = { version = "0.24.7", default-features = false, features = ["jpeg", "png", "avif"] }
include_dir = { version = "0.7.3" }
itertools = "0.12.0"
kamadak-exif = "0.5.5"
memmem = "0.1.1"
mime = "0.3.17"
mime_guess = "2.0.4"
opentelemetry = "0.21.0"
opentelemetry-jaeger = "0.20.0"
ordered-float = "4.2.0"
priority-queue = "1.3.2"
regex = "1.10.2"
serde = { version = "1.0.193", features = ["derive"] }
serde_with = "3.4.0"
serde_yaml = "0.9.29"
sha1_smol = "1.0.0"
sqlx = { version = "0.7.3", features = ["chrono", "sqlite", "migrate", "uuid", "macros", "runtime-tokio"], default-features = false }
tempfile = "3.8.1"
tokio = { version = "1.35.1", features = ["full"] }
tower = { version = "0.4.13", features = ["util"] }
tower-http = { version = "0.5.0", features = ["fs", "util", "compression-gzip", "set-header", "trace"] }
tracing = "0.1.40"
tracing-flame = "0.2.0"
tracing-opentelemetry = "0.22.0"
tracing-subscriber = { version = "0.3.18", features = ["fmt", "env-filter"] }
walkdir = "2.4.0"
