[package]
name = "pica_image"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
byteorder = "1.5.0"
chrono = "0.4.41"
hex-literal = "1.0.0"
kamadak-exif = "0.6.1"
tempfile = "3.20.0"
tracing = "0.1.41"

[dev-dependencies]
tracing-subscriber = "0.3.19"
