[package]
name = "pica_image"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
byteorder = "1.5.0"
chrono = "0.4.33"
hex-literal = "0.4.1"
kamadak-exif = "0.5.5"
tempfile = "3.9.0"
tracing = "0.1.40"

[dev-dependencies]
tracing-subscriber = "0.3.18"
