name: Binaries

on:
  push:
    tags: v*
    branches: [main]

jobs:
  Build:
    strategy:
      matrix:
        config:
          - platform: linux/amd64
            tag: linux-amd64
          - platform: linux/arm64
            tag: linux-arm64

    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.config.platform }}
          load: true
          tags: pica:${{ matrix.config.tag }}

      - name: Extract binary from container image
        run: |
          ID=$(docker create pica:${{ matrix.config.tag }})
          docker cp $ID:/app/pica pica-${{ matrix.config.tag }}

      - name: Archive pica binary
        uses: actions/upload-artifact@v4
        with:
          name: pica-${{ matrix.config.tag }}
          path: pica-${{ matrix.config.tag }}

  Release:
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - name: Download previously created artifacts
        uses: actions/download-artifact@v4
        with:
          name: pica-linux-amd64

      - name: Download previously created artifacts
        uses: actions/download-artifact@v4
        with:
          name: pica-linux-arm64

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            pica-linux-amd64
            pica-linux-arm64

